### ISSUE TITLE
AttributeError: module 'FixaTons' has no attribute 'info'

### ISSUE THREAD

**Issue by kmamine** [dariozanca/FixaTons#2]
FixaTons.info.datasets()
Traceback (most recent call last):

  File "<ipython-input-114-30a772427f1f>", line 1, in <module>
    FixaTons.info.datasets()

AttributeError: module 'FixaTons' has no attribute 'info'

**Comment by dariozanca** [comment]
How did you import the library?

**Comment by dariozanca** [comment]
I double checked and it works fine. 

Make sure you are you are using python 3 and importing FixaTons properly. 

Please refer to the jupyter tutorial for a correct import and usage of the package.
